### ISSUE TITLE
No provider metadata found

### ISSUE THREAD

**Issue by MrNuggelz** [jellyfin/jellyfin-plugin-autoorganize#13]
When trying to organize episodes the plugin returns the error "No provider metadata found for someShow season someSeason episode someEpisode". This originates from the following line:

https://github.com/jellyfin/jellyfin-plugin-autoorganize/blob/ef7588123ba74b5940d99b57015400f6e2945c19/Emby.AutoOrganize/Core/EpisodeFileOrganizer.cs#L933

**Comment by peroksid5** [comment]
Get the same error for Autoorganize 4.0.0.0 for TV series in Jellyfin 10.3.7 (Docker on Synology). For Movies it works.

**Comment by stewemetal** [comment]
The same thing happens when I'm trying to organize TV series episodes. Jellyfin 10.3.7 on RPi (Raspbian Stretch).
Movie sorting works indeed.

**Comment by anthonylavado** [comment]
Just to be sure, what providers do you have enabled in your tv libraries?

**Comment by stewemetal** [comment]
Well, I enabled all of them. To be honest, I haven't tested every linear combination of them to see if either of them is a suspect.
![image](https://user-images.githubusercontent.com/5860632/65956149-012dc380-e44a-11e9-9bb8-2b8b3271b73f.png)
![image](https://user-images.githubusercontent.com/5860632/65956162-0ab72b80-e44a-11e9-8642-5220e94e6a68.png)

**Comment by stewemetal** [comment]
I had a little time to fiddle with the providers. Enabling only TheTVDB and TheMovieDB yields the same result.
