### ISSUE TITLE
Getting this error:  "No provider metadata found for..."

### ISSUE THREAD

**Issue by chilman408** [jellyfin/jellyfin-plugin-autoorganize#22]
Is this plugin working for anybody in Jellyfin 10.4.3?  

I'm getting this error "No provider metadata found for..." but if I copy the files to the destination manually, the metadata populates fine.

Could it be that my library destination is on a networked drive?

**Comment by anthonylavado** [comment]
No, it’s an update that’s required in the main code. It‘a not just you :-)

See #20.
