### ISSUE TITLE
what does this plug in do?

### ISSUE THREAD

**Issue by ghost** [jellyfin/jellyfin-plugin-autoorganize#6]
Just wondering what this does? looking around at some of the plugins and im a bit lost as to what they all do the readme isnt very descriptive.

**Comment by anthonylavado** [comment]
Yes, we'll have to update that. Essentially - it's a file organizer. So if you don't have your stuff already sorted in folders, etc., this can do that for you.

**Comment by nickcorona** [comment]
> Yes, we'll have to update that. Essentially - it's a file organizer. So if you don't have your stuff already sorted in folders, etc., this can do that for you.

Doesn't Jellyfin already do this by default? I'm confused.
