### ISSUE TITLE
docker: System.TypeInitializationException: The type initializer for 'Emby.AutoOrganize.Data.BaseSqliteRepository' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'SQLitePCL.pretty, Version=1.1.8.0, Culture=neutral, PublicKeyToken=null'

### ISSUE THREAD

**Issue by ssbarnea** [jellyfin/jellyfin-plugin-autoorganize#8]
This error can be seen in the log when running jellyfin official docker distributions:

> System.TypeInitializationException: The type initializer for 'Emby.AutoOrganize.Data.BaseSqliteRepository' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'SQLitePCL.pretty, Version=1.1.8.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
> jellyfin_1  |
>

**Comment by ssbarnea** [comment]
Mainly this tells me that the plugin is missing a critical dependency.

**Comment by MrNuggelz** [comment]
The strange thing is that the "SQLitePCL.pretty.dll" file exists in the jellyfin directory, at least in the docker version. Maybe it's a wrong version, but I don't know how to test that.

**Comment by cvium** [comment]
It's the wrong nuget package. It should be https://www.nuget.org/packages/SQLitePCL.pretty.netstandard/

**Comment by MrNuggelz** [comment]
Thanks much, that solved the problem

**Comment by MrNuggelz** [comment]
This is fixed by #10
